In [1]:
import torch


In [11]:
x = torch.randint(2, 4, (2,3))
y = torch.randint(2,4, (2,3))
print(x)
print(y)

tensor([[2, 3, 2],
        [3, 3, 2]])
tensor([[3, 2, 3],
        [3, 3, 3]])


In [12]:
x.add_(-1, y)

tensor([[-1,  1, -1],
        [ 0,  0, -1]])